### ISSUE TITLE
How to use with blueprints

### ISSUE THREAD

**Issue by sondrelg** [aws-ia/terraform-aws-eks-blueprints-teams#13]
Hi,

I've just tried setting up a new team for my cluster, and the clusterbindings etc., all seem to be set up as expected. However, unlike when setting up a `platform-team` in the eks-blueprints module, no role seems to have been created in the AWS IAM console. 

I tried to look at the example provided in this repository, and [this section](https://github.com/aws-ia/terraform-aws-eks-blueprints-teams/blob/main/tests/complete/main.tf#L231) seems relevant. However, the example is given using the `eks` module rather than the blueprints one, so I'm not sure how to apply it in my case.

Is this module compatible with the [eks-blueprints](https://github.com/aws-ia/terraform-aws-eks-blueprints) module, and if so, how should they be used together?

**Comment by bryantbiggs** [comment]
yes it is compatible - instead of passing the values shown in the example linked to `aws_auth_roles`, you would pass them to `map_roles`
