### ISSUE TITLE
Feature request: add Condition variable

### ISSUE THREAD

**Issue by Almenon** [aws-ia/terraform-aws-eks-blueprints-teams#15]
Using AWS IAM Identity Center is best practice according to AWS for assigning out permissions. However, it creates roles with unique names. To avoid having to hardcode unique names everywhere, AWS says you can use a condition with a wildcard in your trust policy. However, terraform-aws-eks-blueprints-teams does not support that currently. 

If this repo added support that would make our code a lot cleaner and more maintainable, as we wouldn't have to have hardcoded AWS role names for each AWS account.

For reference see bottom of https://docs.aws.amazon.com/singlesignon/latest/userguide/referencingpermissionsets.html

**Comment by bryantbiggs** [comment]
I think that sounds like a reasonable change - we'll add this to the list, thank you!
