### ISSUE TITLE
Option to use an inline policy instead of a managed policy

### ISSUE THREAD

**Issue by nitrocode** [aws-ia/terraform-aws-eks-blueprints-teams#22]
Relevant aws_iam_role code

https://github.com/aws-ia/terraform-aws-eks-blueprints-teams/blob/e039ac2fbcc25f8990965cc298f97208e573e74c/main.tf#L438-L452

---

Compare this which creates a managed iam policy which can be reused accidentally in another role

https://github.com/aws-ia/terraform-aws-eks-blueprints-teams/blob/e039ac2fbcc25f8990965cc298f97208e573e74c/main.tf#L519-L537

vs this example of an inline policy which

- uses 2 fewer resources
- an inline policy which cannot be reused
- an inline policy which does not need to be globally named to avoid a name conflict
- an inline policy which does not need to be tagged

```hcl
resource "aws_iam_role" "this" {
  count = var.create_iam_role ? 1 : 0

  # truncated for brevity

  dynamic "inline_policy" {
    for_each = var.iam_role_use_inline_policy ? [1] : []

    statement {
      name = local.admin_policy_name

      policy = data.aws_iam_policy_document.admin[0].json
    }
  }
}
```

---

Related

- [aws_iam_role](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/iam_role) - add an inline policy in role
- [aws_iam_role_policy](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/iam_role_policy) - inline role policy separate resource

**Comment by bryantbiggs** [comment]
Sorry I'm not quite following - is there an issue or end goal you are trying to resolve?

**Comment by nitrocode** [comment]
Yes. I'd like to create an inline policy instead of a managed policy to avoid a dev from reusing the IAM policy by mistake which would then prevent me from deleting the policy in the future due to its reuse. I can do that by using an inline policy instead of a managed policy.

**Comment by nitrocode** [comment]
Unstale

**Comment by bryantbiggs** [comment]
Why is an inline policy a good idea?

**Comment by nitrocode** [comment]
I don't have much more to add than the above comment https://github.com/aws-ia/terraform-aws-eks-blueprints-teams/issues/22#issuecomment-1751579295

If anything, it's better to default to an inline policy or even convert to an inline policy from a managed policy so the policy cannot be accidentally reused.

Managed policies are for sharing.

Inline policies are for single uses.
