### ISSUE TITLE
Unreadable module directory

### ISSUE THREAD

**Issue by vstthomas** [aws-ia/terraform-aws-eks-blueprints-teams#23]
This little snippet from the TF registry, with the latest version will fail

```hcl
% cat main.tf
module "eks-blueprints-teams_example_complete" {
  source  = "aws-ia/eks-blueprints-teams/aws//examples/complete"
  version = "1.1.0"
}
```

Error:

```sh
Initializing the backend...
Initializing modules...
Downloading registry.terraform.io/aws-ia/eks-blueprints-teams/aws 1.1.0 for eks-blueprints-teams_example_complete...
- eks-blueprints-teams_example_complete in .terraform/modules/eks-blueprints-teams_example_complete/examples/complete
╷
│ Error: Unreadable module directory
│ 
│ The directory .terraform/modules/eks-blueprints-teams_example_complete/examples/complete could not be read. This is a bug in
│ Terraform and should be reported.
```

**Comment by askulkarni2** [comment]
@vstthomas where do you see that snippet?

This is the snippet on the registry page which should work...

```hcl
module "eks-blueprints-teams" {
  source  = "aws-ia/eks-blueprints-teams/aws"
  version = "1.1.0"
}

```

**Comment by vstthomas** [comment]
I found that on the TF registry, as previously stated. Hi the drop-down, select "complete" and copy the "Provision Instructions" block. 

![image](https://github.com/aws-ia/terraform-aws-eks-blueprints-teams/assets/146481625/082bfee1-b427-459d-8265-cfc2a52dc6b7)

![image](https://github.com/aws-ia/terraform-aws-eks-blueprints-teams/assets/146481625/33234bbe-66a5-44de-9316-cff0666e8e02)

I will try it without the "complete" example. But, the complete example should work. Please fix that while I test the suggested one.

**Comment by bryantbiggs** [comment]
I think thats a Terraform registry bug - we don't control the registry, we simply publish modules to it. Also, examples are not modules and not meant to be consumed the same fashion as a module

**Comment by vstthomas** [comment]
sorry, it hadn't occurred to me that bug would still be lingering 😬
